In [1]:
import numpy as np

In [2]:
a = np.array([[2, -6, -1],
              [-3, -1, 7],
              [-8, 1, -2]], dtype=float)
b = np.array([[-38],
              [-34],
              [-40]],dtype=float)
np.linalg.solve(a, b)

array([[ 6.30563003],
       [ 8.58981233],
       [-0.92761394]])

In [13]:
def lu_factorization(A):

    # Get the number of rows
    n = A.shape[0]
    
    # Initialize P, L, and U
    P = np.eye(n)
    L = np.eye(n)
    U = A.copy()
    
    for i in range(n):
      
        # Perform elimination to make entries below the pivot equal to zero
        for j in range(i + 1, n):
            factor = U[j, i] / U[i, i]
            U[j, i:] -= factor * U[i, i:]
            L[j, i] = factor
    
    return P, L, U
    

In [12]:
lu_factorization(a)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[ 1. ,  0. ,  0. ],
        [-1.5,  1. ,  0. ],
        [-4. ,  2.3,  1. ]]),
 array([[  2.  ,  -6.  ,  -1.  ],
        [  0.  , -10.  ,   5.5 ],
        [  0.  ,   0.  , -18.65]]))

In [5]:
def forward_substitution(aug_matrix):
    nrows = aug_matrix.shape[0]
    solutions = np.zeros(nrows)
    for i in range(nrows):
        solutions[i] = (aug_matrix[i][nrows] - np.dot(aug_matrix[i][:3], solutions))/aug_matrix[i][i] 
        
    return solutions

In [6]:
def back_substitution(aug_matrix):
    nrows = aug_matrix.shape[0]
    solutions = np.zeros(nrows)
    for i in range(nrows - 1, -1, -1):
        solutions[i] = (aug_matrix[i][nrows] - np.dot(aug_matrix[i][:3], solutions))/aug_matrix[i][i] 
    
    return solutions

In [7]:
def lu_solve(l, u, b):
    det_A = np.linalg.det(l)*np.linalg.det(u)
    lb = np.concatenate((l, b), axis=1)
    y = forward_substitution(lb)
    y = y.reshape((len(y), 1))
    uy = np.concatenate((u, y), axis=1)
    solution = back_substitution(uy)
    return solution

In [8]:
def solve_lu_factorization_with_pivoting(a, b):
    p, l, u = lu_factorization(a)
    print(l)
    print(u)
    return lu_solve(l, u, b)

In [9]:
x_1, x_2, x_3 = solve_lu_factorization_with_pivoting(a, b)
x_1

[[ 1.          0.          0.        ]
 [-0.25        1.          0.        ]
 [ 0.375       0.23913043  1.        ]]
[[-8.          1.         -2.        ]
 [ 0.         -5.75       -1.5       ]
 [ 0.          0.          8.10869565]]


np.float64(6.230563002680965)

In [10]:
np.linalg.solve(a, b)

array([[ 6.30563003],
       [ 8.58981233],
       [-0.92761394]])