In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.array([[4, 7], [1, 2], [5, 6]])
B = np.array([[4, 3, 7], [1, 2, 7], [2, 0, 4]])
C = np.array([[3], [6], [1]])
D = np.array([[9, 4, 3, -6], [2, -1, 7, 5]])
E = np.array([[1, 5, 8], [7, 2, 3], [4, 0, 6]])
F = np.array([[3, 0, 1], [1, 7, 3]])
G = np.array([7, 6, 4])

In [20]:
print(E + B)

[[ 5  8 15]
 [ 8  4 10]
 [ 6  0 10]]


In [4]:
B-E

array([[ 3, -2, -1],
       [-6,  0,  4],
       [-2,  0, -2]])

In [5]:
7*B

array([[28, 21, 49],
       [ 7, 14, 49],
       [14,  0, 28]])

In [6]:
C.T

array([[3, 6, 1]])

In [7]:
E@B

array([[25, 13, 74],
       [36, 25, 75],
       [28, 12, 52]])

In [8]:
np.matmul(E, B)

array([[25, 13, 74],
       [36, 25, 75],
       [28, 12, 52]])

In [9]:
B@A

array([[54, 76],
       [41, 53],
       [28, 38]])

In [10]:
D.T

array([[ 9,  2],
       [ 4, -1],
       [ 3,  7],
       [-6,  5]])

In [16]:
I3 = np.identity(3)

In [17]:
I3@B

array([[4., 3., 7.],
       [1., 2., 7.],
       [2., 0., 4.]])

In [18]:
E.T@E

array([[ 66,  19,  53],
       [ 19,  29,  46],
       [ 53,  46, 109]])

In [19]:
C.T@C

array([[46]])