In [1]:
import numpy as np

In [2]:
A = np.array([[0, -3, 7],
              [1, 2, -1],
              [5, -2, 0]], dtype=float)
B = np.array([[4],
              [0],
              [3]], dtype=float)

In [3]:
# Solution to check
solution = np.linalg.solve(A, B)
solution

array([[ 0.5942029 ],
       [-0.01449275],
       [ 0.56521739]])

### Cramer's Rule Function

In [4]:
def cramer(a, b, return_matrices=False):
    a_nrows = a.shape[0]
    b_nrows = b.shape[0]
    if a_nrows != b_nrows:
        raise ValueError("Incorrect shapes. Check matrix shapes and try again")
    det_A = np.linalg.det(A)
    matrices = []
    solutions = np.zeros(a_nrows)

    for i in range(a_nrows):
        matrices.append(a.copy())
        matrices[i][:, i] = b[:, 0]
        solutions[i] = np.linalg.det(matrices[i])/det_A
        
    if return_matrices:
        return matrices, solutions
    
    else: 
        return solutions

In [5]:
x_1_cramer, x_2_cramer, x_3_cramer = cramer(A, B)
x_1_cramer, x_2_cramer, x_3_cramer

(np.float64(0.5942028985507251),
 np.float64(-0.014492753623188493),
 np.float64(0.5652173913043481))

In [ ]:
# My Gaussian implementation

# def gaussian_elimination_with_pivoting(a, b):
#     a = a.astype(float)
#     b = b.astype(float)
#     nrows = a.shape[0]
#     if np.linalg.det(a) == 0:
#         raise ValueError("Determinant is equal to 0. Guassian elimination does not produce unique solution.")
#     if a.shape[0] != a.shape[1]:
#         raise ValueError("Matrix must be a square matrix")
    
#     solutions = np.zeros(nrows)

#     # Augment the matrix
#     matrix = np.concatenate((a, b), axis=1)

#     # Sort in reverse order "Pivoting"    
#     matrix = matrix[np.argsort(a[:,0])][::-1]

#     # Get values below pivots equal to 0 by doing row ops
#     for i in range(nrows - 1):
#         matrix[i + 1] = matrix[i + 1] - (matrix[i + 1][i]/matrix[i][i])*matrix[i] 
    

#     return matrix[:,:nrows], matrix[:, -1]



In [ ]:
# Thomas's
def gaussian_elimination_with_pivoting(A, B):
    A = A.astype(float)
    B = B.astype(float)
    n = A.shape[0]
    
    for i in range(n):
        # Partial pivoting
        max_row = np.argmax(np.abs(A[i:, i])) + i
        if A[max_row, i] == 0:
            raise ValueError("Matrix is singular, no unique solution exists.")
        
        # Swap rows in both A and B if necessary
        if max_row != i:
            A[[i, max_row]] = A[[max_row, i]]
            B[[i, max_row]] = B[[max_row, i]]
        
        # Eliminate entries below the pivot
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            A[j, i:] -= factor * A[i, i:]
            B[j] -= factor * B[i]
    
    return A, B


In [34]:
def back_substitution(a, b):
    nrows = a.shape[0]
    solutions = np.zeros(nrows)
    for i in range(nrows - 1, -1, -1):
        solutions[i] = (b[i] - np.dot(a[i], solutions))/a[i][i] 
    
    return solutions

In [35]:
new_A, new_B = gaussian_elimination_with_pivoting(A, B)
print("Modified A:\n ", new_A)
print("Modified B:\n ", new_B)

Modified A:
  [[ 5.  -2.   0. ]
 [ 0.  -3.   7. ]
 [ 0.   0.   4.6]]
Modified B:
  [[3. ]
 [4. ]
 [2.6]]


In [24]:
solutions = back_substitution(new_A, new_B)
solutions

C:\Users\Hunter\AppData\Local\Temp\ipykernel_21228\3386322892.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  solutions[i] = (b[i] - np.dot(a[i], solutions))/a[i][i]


array([ 0.5942029 , -0.01449275,  0.56521739])

In [20]:
eq1_hs = -3*solutions[1] + 7*solutions[2]
eq1_hs

np.float64(4.0)

In [21]:
eq2_hs = solutions[0] + 2*solutions[1] - solutions[2]
eq2_hs

np.float64(-1.1102230246251565e-16)

In [12]:
eq3_hs = 5*solutions[0] - 2*solutions[1]
eq3_hs

np.float64(3.0)